### ISSUE TITLE
Heater vs Chiller Logic

### ISSUE THREAD

**Issue by BrauereiAlt** [craftbeerpi/craftbeerpi4#44]
Alexander touched on the need to differentiate between heater logic and chiller logic.  This is applicable not only to fermenters, but boil kettles as well.  Some of us want to pre-boil our strike water, chill it to strike temp, and then mash in.  At the end of the boil, we would like to be able to whirlpool within the boil kettle with a minimum temperature set point and then begin chilling while still recirculating.

I propose that a chiller actor be added to the kettle class and a chill step to steps.  In the hysteresis logic, when the heater is turned on, the chiller is turned off.  Conversely, when the heater is turned off, the chiller is turned on.  I also suggest renaming the variables offset_on and offset_off to offset_low and offset_high, respectively.  Each program step should determine whether the heater, chiller or both are enabled for that step.  The user should be free to manually enable either or both at any time.  I presume in time a fermentation step will be added as well.

**Comment by avollkopf** [comment]
@BrauereiAlt  i think this would need to be done with a separate logic. I am currently working on a cool down step which also calculates the estimated time on when the target temperature is reached. I would just need to add an actor that could be configured for those who require it. You would need to configure two steps anyhow. On to heat up the water to boil and a second that is cooling it to target temp.

**Comment by avollkopf** [comment]
@BrauereiAlt  This should have been solved with the cooldown step?
