### ISSUE TITLE
[feature request] multiple Dashboards

### ISSUE THREAD

**Issue by Prash3r** [craftbeerpi/craftbeerpi4#45]
**our use case:** we brew in a HERMS System with a single heat exchanger and thus we move our heat exchanger multiple times during one brewing process. (it is mounted to a lid)

**inconvinience:** It is hard to represent a moving heat exchanger and our wildly dynamic piping setup with the single Dashboard setup.

**requested feature:** I would love to be able to save multiple Dashboards and switch between them either to just look at them or set them as active/default.

This would make our brewing process a lot easier and it would also provide a visual piping check.

**Comment by avollkopf** [comment]
Multiple dashboards have been added. Link to access a dashboard directly might be added in future

**Comment by avollkopf** [comment]
With latest change in UI, you have the possibility to access a dashboard via a fix link : https://github.com/craftbeerpi/craftbeerpi4-ui/commit/e40fafda552405368141a54a24890f9dc8613a94

Example: http://serverip:8000/cbpi_ui/static/index.html#/fixdash/3 -> will load directly dashboard 3
