### ISSUE TITLE
Implementing MQTT Support

### ISSUE THREAD

**Issue by michluk** [craftbeerpi/craftbeerpi4#52]
Hi @Manuel83, 

My intention is to look into implementing some MQTT Support (either as Sensor, Actor or maybe also some kind of API).

There are already some lines of code corresponding to MQTT stuff. Are they so far up-to-date? Do you already have some plans how to design MQTT Support or may I just start from scratch?

Also, the MQTT Server Setup should go into some "deeper" Config (e.g. into the config.json file which contains Author, Brewery, etc.) instead of the Config for the Sensor/Actor. So that it can be configured through the UI for all MQTT devices at the same time. How should I handle this the best way?

Best, 
Lukas

**Comment by Manuel83** [comment]
Hi

I wlll add MQTT support out of the box. 
In a first step I will push Sensor, Actor and Notification data.

Second step is to switch actors on and off.

**Comment by michluk** [comment]
Alright, thanks. If you already have plans, I won’t go any deeper into this topic.

If you need any assistance just let me know!

**Comment by avollkopf** [comment]
MQTT should be all set with latest versios of server
