### ISSUE TITLE
Changing Settings via UI in builtin MQTT_Sensor Plugin triggers asyncio.CancelledError

### ISSUE THREAD

**Issue by chr2002qw** [craftbeerpi/craftbeerpi4#70]
Changing Settings in MQTT Plugin or saving unchanged settings triggers "asyncio.CancelledError" in satellite_controller.py on line 69.
The Plugin is stopped then. After restarting cbpi4 the plugin works again.

I commented out the "return" on line 70 for testing. Then the Plugin keeps running.

After saving changes the plugin read strange json data for about 5 seconds "{"state": "on", "power": 100}"
It seems this data is comming from cbpi´s own MQTT Publishes. After 5 seconds the correct Json Value is displayed.

I dont care about the full payload string itself for now, i know it needs to be procressed in the Plugin first to get only the temperature instead of the full json paylod.

This issue is only related to the asyncio.CancelledError.

**Comment by avollkopf** [comment]
No issues with latest versions of server observed.
