### ISSUE TITLE
Suggestion: Slide bar for Actor Control

### ISSUE THREAD

**Issue by mariopareto** [craftbeerpi/craftbeerpi4#89]
Hi Manuel!

First of all thank you very much for putting so much effort on CBPI!

I'd like to suggest to implement a slide bar, such as the one that appears when you click "set target temp" for a kettle, as a substitute for the tiny field & up/down arrows that shows up when you click to set power for an actuator.

I think that lots of brewers run CBPI on small touch-screen LCDs and the slide bars are waaay quickier to set, specially when you are reaching a boil-over and need to trim the heating element power.

![image](https://user-images.githubusercontent.com/52330948/157748695-83a6c1ae-af00-48c2-88bd-f59ce4fb19fa.png)
![image](https://user-images.githubusercontent.com/52330948/157748798-b9bb0e15-f372-4fad-8f10-8353f3f6db01.png)

**Comment by msfuture** [comment]
Full support for your idea! We upgraded to craftbeerpi4 on a brewery in our school and everything is controlled by a touchscreen (keyboards tend to break with all those fluids everywhere ;-) )... 
This would improve the usability very much!

**Comment by avollkopf** [comment]
This issue has been also opened for the ui (https://github.com/craftbeerpi/craftbeerpi4-ui/issues/9) and needs to solved there if feasible
